name: Release Wasm Chain Wallet Lib package

on:
  push:
    # Remove branches after testing is complete.
    branches: [ "feature/npg-3884-setup-js-ci-test" ]
    tags:
        # walletjs-0.7.0-beta
      - walletjs-*

jobs:
  initial_release:
    name: Create base release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Set version output
        id: get_version
        run: echo ::set-output name=version::``${GITHUB_REF#refs/tags/}``

  release_wasm:
    name: Release wasm assets
    needs: initial_release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # target: [nodejs, web, bundler]
        target: [nodejs]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'

      - name: Install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          cd src/chain-wallet-libs
          wasm-pack build \
            --scope catalystcore \
            --out-name walletjs \
            --release --target ${{ matrix.target }} \
            bindings/wallet-js

      - name: Run tests
        run: |
          cd src/chain-wallet-libs/bindings/wallet-js/js-test
          npm install
          npm test

      # - name: Pack
      #   run: |
      #     cd src/chain-wallet-libs
      #     wasm-pack pack bindings/wallet-js

      # - name: Publish
      #   run: |
      #     cd src/chain-wallet-libs/bindings/wallet-js/pkg
      #     npm publish --access=public
      #   env:
      #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}